/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Interfaces;

import java.awt.Color;
import java.awt.Font;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author xbyro
 */
public class Empleados extends javax.swing.JInternalFrame {

    public Connection Conectar() {
        Connection conn = null;

        try {
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/sistemafacturacion", "root", "Wolfhack0504");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No se puedo realizar la conexion" + e.toString());
        }
        return conn;
    }

    DefaultTableModel modelo;

    public Empleados() {
        initComponents();
        infoTable.getTableHeader().setFont(new Font("Roboto Light", Font.BOLD, 14));
        infoTable.getTableHeader().setOpaque(false);
        infoTable.getTableHeader().setBackground(new Color(32, 136, 203));
        infoTable.getTableHeader().setForeground(new Color(255, 255, 255));
        infoTable.setRowHeight(25);

        modelo = new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellido");
        modelo.addColumn("Telefono");
        modelo.addColumn("Email");
        this.infoTable.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        logoIcon = new javax.swing.JLabel();
        registerText = new javax.swing.JLabel();
        nameText = new javax.swing.JLabel();
        typeName = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        apellidoText = new javax.swing.JLabel();
        typeApellido = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        phoneText = new javax.swing.JLabel();
        typePhone = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        emailText = new javax.swing.JLabel();
        typeEmail = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        table = new javax.swing.JScrollPane();
        infoTable = new javax.swing.JTable();
        newBtn = new javax.swing.JPanel();
        newText = new javax.swing.JLabel();
        deleteBtn = new javax.swing.JPanel();
        deleteText = new javax.swing.JLabel();
        updateBtn = new javax.swing.JPanel();
        updateText = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(910, 690));

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setPreferredSize(new java.awt.Dimension(910, 690));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemafacturacion/imagenes/LogoEmpresa (1).png"))); // NOI18N
        logoIcon.setText("jLabel3");
        bg.add(logoIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 180, 50));

        registerText.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        registerText.setText("Registro de Empleados");
        bg.add(registerText, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        nameText.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        nameText.setText("Nombre:");
        bg.add(nameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        typeName.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        typeName.setForeground(new java.awt.Color(153, 153, 153));
        typeName.setText("Ingrese el nombre del empleado");
        typeName.setBorder(null);
        typeName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                typeNameMousePressed(evt);
            }
        });
        typeName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeNameActionPerformed(evt);
            }
        });
        bg.add(typeName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 210, 30));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 220, 20));

        apellidoText.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        apellidoText.setText("Apellido:");
        bg.add(apellidoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        typeApellido.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        typeApellido.setForeground(new java.awt.Color(153, 153, 153));
        typeApellido.setText("Ingrese los apellidos del empleado");
        typeApellido.setBorder(null);
        typeApellido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                typeApellidoMousePressed(evt);
            }
        });
        bg.add(typeApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 220, 30));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 220, 20));

        phoneText.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        phoneText.setText("Telefono:");
        bg.add(phoneText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        typePhone.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        typePhone.setForeground(new java.awt.Color(153, 153, 153));
        typePhone.setText("70254804");
        typePhone.setBorder(null);
        typePhone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                typePhoneMousePressed(evt);
            }
        });
        bg.add(typePhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 210, 30));

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 220, 20));

        emailText.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        emailText.setText("Email:");
        bg.add(emailText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        typeEmail.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        typeEmail.setForeground(new java.awt.Color(153, 153, 153));
        typeEmail.setText("example@gmail.com");
        typeEmail.setBorder(null);
        typeEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                typeEmailMousePressed(evt);
            }
        });
        typeEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeEmailActionPerformed(evt);
            }
        });
        bg.add(typeEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 210, 30));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 220, 20));

        infoTable.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        infoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Apellido", "Telefono", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        infoTable.setFocusable(false);
        infoTable.setRowHeight(25);
        infoTable.setSelectionBackground(new java.awt.Color(232, 57, 95));
        infoTable.setSelectionForeground(new java.awt.Color(255, 255, 255));
        infoTable.setShowGrid(false);
        infoTable.setShowHorizontalLines(true);
        infoTable.getTableHeader().setReorderingAllowed(false);
        table.setViewportView(infoTable);

        bg.add(table, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 590, 290));

        newBtn.setBackground(new java.awt.Color(1, 73, 97));

        newText.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        newText.setForeground(new java.awt.Color(255, 255, 255));
        newText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newText.setText("Nueva");
        newText.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        newText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                newTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                newTextMouseExited(evt);
            }
        });

        javax.swing.GroupLayout newBtnLayout = new javax.swing.GroupLayout(newBtn);
        newBtn.setLayout(newBtnLayout);
        newBtnLayout.setHorizontalGroup(
            newBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newBtnLayout.createSequentialGroup()
                .addComponent(newText, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        newBtnLayout.setVerticalGroup(
            newBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(newText, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        );

        bg.add(newBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 450, 140, -1));

        deleteBtn.setBackground(new java.awt.Color(1, 73, 97));

        deleteText.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        deleteText.setForeground(new java.awt.Color(255, 255, 255));
        deleteText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        deleteText.setText("Eliminar");
        deleteText.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deleteTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deleteTextMouseExited(evt);
            }
        });

        javax.swing.GroupLayout deleteBtnLayout = new javax.swing.GroupLayout(deleteBtn);
        deleteBtn.setLayout(deleteBtnLayout);
        deleteBtnLayout.setHorizontalGroup(
            deleteBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteBtnLayout.createSequentialGroup()
                .addComponent(deleteText, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        deleteBtnLayout.setVerticalGroup(
            deleteBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(deleteText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        );

        bg.add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 450, -1, -1));

        updateBtn.setBackground(new java.awt.Color(1, 73, 97));

        updateText.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        updateText.setForeground(new java.awt.Color(255, 255, 255));
        updateText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        updateText.setText("Actualizar");
        updateText.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updateText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updateTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updateTextMouseExited(evt);
            }
        });

        javax.swing.GroupLayout updateBtnLayout = new javax.swing.GroupLayout(updateBtn);
        updateBtn.setLayout(updateBtnLayout);
        updateBtnLayout.setHorizontalGroup(
            updateBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateBtnLayout.createSequentialGroup()
                .addComponent(updateText, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        updateBtnLayout.setVerticalGroup(
            updateBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(updateText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        );

        bg.add(updateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 450, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 911, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void typeEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeEmailActionPerformed

    private void newTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newTextMouseClicked
        // Falta Definir que sigue
        String[] datos = new String[8];
        datos[0] = "1"; //Aqui va el ID de la propiedad ud verá como lo extrae de la base de datos
        datos[1] = typeName.getText();
        datos[2] = typeApellido.getText();
        datos[3] = typePhone.getText();
        datos[4] = typeEmail.getText();
        modelo.addRow(datos);

        typeName.setText("Ingrese el nombre del empleado");
        typeName.setForeground(Color.gray);
        typeApellido.setText("Ingrese los apellidos del empleado");
        typeApellido.setForeground(Color.gray);
        typePhone.setText("70254804");
        typePhone.setForeground(Color.gray);
        typeEmail.setText("example@gmail.com");
        typeEmail.setForeground(Color.gray);
    }//GEN-LAST:event_newTextMouseClicked

    private void newTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newTextMouseEntered
        // TODO add your handling code here:
        newBtn.setBackground(new Color(2, 123, 164));
    }//GEN-LAST:event_newTextMouseEntered

    private void newTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newTextMouseExited
        // TODO add your handling code here:
        newBtn.setBackground(new Color(1, 73, 97));
    }//GEN-LAST:event_newTextMouseExited

    private void deleteTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteTextMouseClicked
        // TODO add your handling code here:
        int fila = infoTable.getSelectedRow();
        if (fila >= 0) {
            modelo.removeRow(fila);
        } else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar una fila para poder eliminar.");
        }
    }//GEN-LAST:event_deleteTextMouseClicked

    private void deleteTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteTextMouseEntered
        // TODO add your handling code here:
        deleteBtn.setBackground(new Color(2, 123, 164));
    }//GEN-LAST:event_deleteTextMouseEntered

    private void deleteTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteTextMouseExited
        // TODO add your handling code here:
        deleteBtn.setBackground(new Color(1, 73, 97));
    }//GEN-LAST:event_deleteTextMouseExited

    private void updateTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateTextMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_updateTextMouseClicked

    private void updateTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateTextMouseEntered
        // TODO add your handling code here:
        updateBtn.setBackground(new Color(2, 123, 164));
    }//GEN-LAST:event_updateTextMouseEntered

    private void updateTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateTextMouseExited
        // TODO add your handling code here:
        updateBtn.setBackground(new Color(1, 73, 97));
    }//GEN-LAST:event_updateTextMouseExited

    private void typeNameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_typeNameMousePressed
        // TODO add your handling code here:
        if (typeName.getText().equals("Ingrese el nombre del empleado")) {
            typeName.setText("");
            typeName.setForeground(Color.black);

        }

        if (typeApellido.getText().isEmpty()) {
            typeApellido.setText("Ingrese los apellidos del empleado");
            typeName.setForeground(Color.gray);

        }

        if (typePhone.getText().isEmpty()) {
            typePhone.setText("70254804");
            typePhone.setForeground(Color.gray);

        }

        if (typeEmail.getText().isEmpty()) {
            typeEmail.setText("example@gmail.com");
            typeEmail.setForeground(Color.gray);

        }
    }//GEN-LAST:event_typeNameMousePressed

    private void typeNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeNameActionPerformed

    private void typeApellidoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_typeApellidoMousePressed
        // TODO add your handling code here:
        if (typeName.getText().isEmpty()) {
            typeName.setText("Ingrese el nombre del cliente");
            typeName.setForeground(Color.gray);

        }

        if (typeApellido.getText().equals("Ingrese los apellidos del empleado")) {
            typeApellido.setText("");
            typeName.setForeground(Color.black);

        }

        if (typePhone.getText().isEmpty()) {
            typePhone.setText("70254804");
            typePhone.setForeground(Color.gray);

        }

        if (typeEmail.getText().isEmpty()) {
            typeEmail.setText("example@gmail.com");
            typeEmail.setForeground(Color.gray);

        }
    }//GEN-LAST:event_typeApellidoMousePressed

    private void typePhoneMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_typePhoneMousePressed
        // TODO add your handling code here:
        if (typeName.getText().isEmpty()) {
            typeName.setText("Ingrese el nombre del cliente");
            typeName.setForeground(Color.gray);

        }

        if (typeApellido.getText().isEmpty()) {
            typeApellido.setText("Ingrese los apellidos del cliente");
            typeName.setForeground(Color.gray);

        }

        if (typePhone.getText().equals("70254804")) {
            typePhone.setText("");
            typePhone.setForeground(Color.black);

        }

        if (typeEmail.getText().isEmpty()) {
            typeEmail.setText("example@gmail.com");
            typeEmail.setForeground(Color.gray);

        }
    }//GEN-LAST:event_typePhoneMousePressed

    private void typeEmailMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_typeEmailMousePressed
        // TODO add your handling code here:
        if (typeName.getText().isEmpty()) {
            typeName.setText("Ingrese el nombre del cliente");
            typeName.setForeground(Color.gray);

        }

        if (typeApellido.getText().isEmpty()) {
            typeApellido.setText("Ingrese los apellidos del cliente");
            typeName.setForeground(Color.gray);

        }

        if (typePhone.getText().isEmpty()) {
            typePhone.setText("70254804");
            typePhone.setForeground(Color.gray);

        }

        if (typeEmail.getText().equals("example@gmail.com")) {
            typeEmail.setText("");
            typeEmail.setForeground(Color.black);

        }
    }//GEN-LAST:event_typeEmailMousePressed

//Table vendedores
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apellidoText;
    private javax.swing.JPanel bg;
    private javax.swing.JPanel deleteBtn;
    private javax.swing.JLabel deleteText;
    private javax.swing.JLabel emailText;
    private javax.swing.JTable infoTable;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel logoIcon;
    private javax.swing.JLabel nameText;
    private javax.swing.JPanel newBtn;
    private javax.swing.JLabel newText;
    private javax.swing.JLabel phoneText;
    private javax.swing.JLabel registerText;
    private javax.swing.JScrollPane table;
    private javax.swing.JTextField typeApellido;
    private javax.swing.JTextField typeEmail;
    private javax.swing.JTextField typeName;
    private javax.swing.JTextField typePhone;
    private javax.swing.JPanel updateBtn;
    private javax.swing.JLabel updateText;
    // End of variables declaration//GEN-END:variables
}
