/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import java.awt.Color;
import static java.awt.Color.black;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author gblan
 */
public class InicioSesion extends javax.swing.JFrame {

    /**
     * Creates new form InicioSesion
     */
    int xPos, yPos;

    private String nombre;

    public Connection Conectar() {
        Connection conn = null;

        try {
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/sistemafacturacion", "root", "Wolfhack0504");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No se puedo realizar la conexion" + e.toString());
        }
        return conn;
    }

    public InicioSesion() {
        initComponents();
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        bgBlue = new javax.swing.JLabel();
        LogoL = new javax.swing.JLabel();
        LogText = new javax.swing.JLabel();
        userText = new javax.swing.JLabel();
        typeUser = new javax.swing.JTextField();
        passText = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        typePass = new javax.swing.JPasswordField();
        jSeparator3 = new javax.swing.JSeparator();
        bglogButton = new javax.swing.JPanel();
        logTextButton = new javax.swing.JLabel();
        Header = new javax.swing.JPanel();
        exitButton = new javax.swing.JPanel();
        exitText = new javax.swing.JLabel();
        registroText = new javax.swing.JLabel();
        alertaCredenciales = new javax.swing.JLabel();
        alertaCorreo = new javax.swing.JLabel();
        alertaClave = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bgBlue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemafacturacion/imagenes/fondo azul.jpg"))); // NOI18N
        bgBlue.setText("jLabel1");
        bg.add(bgBlue, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 0, 440, 720));

        LogoL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemafacturacion/imagenes/LogoEmpresa (1).png"))); // NOI18N
        LogoL.setText("jLabel1");
        bg.add(LogoL, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 180, 50));

        LogText.setFont(new java.awt.Font("Roboto Black", 1, 36)); // NOI18N
        LogText.setText("INICIAR SESIÓN");
        bg.add(LogText, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        userText.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        userText.setText("EMAIL");
        bg.add(userText, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        typeUser.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        typeUser.setForeground(new java.awt.Color(153, 153, 153));
        typeUser.setText("Ingrese su em@il");
        typeUser.setBorder(null);
        typeUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                typeUserMousePressed(evt);
            }
        });
        typeUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeUserActionPerformed(evt);
            }
        });
        bg.add(typeUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 390, 40));

        passText.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        passText.setText("PASSWORD");
        bg.add(passText, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 530, 10));

        typePass.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        typePass.setForeground(new java.awt.Color(153, 153, 153));
        typePass.setText("**********");
        typePass.setBorder(null);
        typePass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                typePassMousePressed(evt);
            }
        });
        bg.add(typePass, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 540, 40));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 530, 10));

        bglogButton.setBackground(new java.awt.Color(1, 73, 97));

        logTextButton.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        logTextButton.setForeground(new java.awt.Color(255, 255, 255));
        logTextButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logTextButton.setText("SIGN IN");
        logTextButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logTextButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logTextButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logTextButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logTextButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                logTextButtonMousePressed(evt);
            }
        });

        javax.swing.GroupLayout bglogButtonLayout = new javax.swing.GroupLayout(bglogButton);
        bglogButton.setLayout(bglogButtonLayout);
        bglogButtonLayout.setHorizontalGroup(
            bglogButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logTextButton, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );
        bglogButtonLayout.setVerticalGroup(
            bglogButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logTextButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        bg.add(bglogButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, 250, 50));

        Header.setBackground(new java.awt.Color(255, 255, 255));
        Header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                HeaderMouseDragged(evt);
            }
        });
        Header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HeaderMousePressed(evt);
            }
        });

        exitButton.setBackground(new java.awt.Color(255, 255, 255));

        exitText.setBackground(new java.awt.Color(255, 255, 255));
        exitText.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        exitText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitText.setText("X");
        exitText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitTextMouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitButtonLayout = new javax.swing.GroupLayout(exitButton);
        exitButton.setLayout(exitButtonLayout);
        exitButtonLayout.setHorizontalGroup(
            exitButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitText, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        exitButtonLayout.setVerticalGroup(
            exitButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1230, Short.MAX_VALUE))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        bg.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 50));

        registroText.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        registroText.setText("¿No tienes cuenta? Regístrate");
        registroText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registroTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registroTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registroTextMouseExited(evt);
            }
        });
        bg.add(registroText, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 560, -1, -1));

        alertaCredenciales.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        alertaCredenciales.setForeground(new java.awt.Color(255, 255, 255));
        alertaCredenciales.setText("*Usuario o contraseña incorrectos, vuelva a intentarlo");
        bg.add(alertaCredenciales, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 630, 490, 50));

        alertaCorreo.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        alertaCorreo.setForeground(new java.awt.Color(255, 255, 255));
        alertaCorreo.setText("*Por favor ingrese su correo");
        bg.add(alertaCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 260, 240, 40));

        alertaClave.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        alertaClave.setForeground(new java.awt.Color(255, 255, 255));
        alertaClave.setText("*Por favor ingrese su clave");
        bg.add(alertaClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 410, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void typeUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeUserActionPerformed

    private void HeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMousePressed
        // TODO add your handling code here:
        xPos = evt.getX();
        yPos = evt.getY();
    }//GEN-LAST:event_HeaderMousePressed

    private void HeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xPos, y - yPos);
    }//GEN-LAST:event_HeaderMouseDragged

    private void exitTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTextMouseClicked
        // TODO add your handling code here:
        System.exit(0);

    }//GEN-LAST:event_exitTextMouseClicked

    private void exitTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTextMouseEntered
        // TODO add your handling code here:
        exitButton.setBackground(Color.red);
        exitText.setForeground(Color.white);
    }//GEN-LAST:event_exitTextMouseEntered

    private void exitTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTextMouseExited
        // TODO add your handling code here:
        exitButton.setBackground(Color.white);
        exitText.setForeground(Color.black);

    }//GEN-LAST:event_exitTextMouseExited

    private void logTextButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logTextButtonMouseEntered
        // TODO add your handling code here:
        bglogButton.setBackground(new Color(2, 123, 164));
    }//GEN-LAST:event_logTextButtonMouseEntered

    private void logTextButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logTextButtonMouseExited
        // TODO add your handling code here:
        bglogButton.setBackground(new Color(1, 73, 97));
    }//GEN-LAST:event_logTextButtonMouseExited

    private void typeUserMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_typeUserMousePressed
        // TODO add your handling code here:user
        if (typeUser.getText().equals("Ingrese su em@il")) {
            typeUser.setText("");
            typeUser.setForeground(Color.black);
        }
        if (String.valueOf(typePass.getPassword()).isEmpty()) {
            typePass.setText("**********");
            typePass.setForeground(Color.gray);
        }


    }//GEN-LAST:event_typeUserMousePressed

    private void typePassMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_typePassMousePressed
        // TODO add your handling code here:
        if (typeUser.getText().isEmpty()) {
            typeUser.setText("Ingrese su em@il");
            typeUser.setForeground(Color.gray);
        }
        if (String.valueOf(typePass.getPassword()).equals("**********")) {
            typePass.setText("");
            typePass.setForeground(Color.black);
        }

    }//GEN-LAST:event_typePassMousePressed

    private void logTextButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logTextButtonMouseClicked
        // Falta Definir que sigue

    }//GEN-LAST:event_logTextButtonMouseClicked

    private void registroTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registroTextMouseEntered
        registroText.setForeground(new Color(1, 73, 97));

    }//GEN-LAST:event_registroTextMouseEntered

    private void registroTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registroTextMouseExited
        registroText.setForeground(black);
    }//GEN-LAST:event_registroTextMouseExited

    private void registroTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registroTextMouseClicked
        // TODO add your handling code here:
        newAccount nA = new newAccount();
        nA.setVisible(true);
        dispose();

    }//GEN-LAST:event_registroTextMouseClicked

    private void logTextButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logTextButtonMousePressed
        // TODO add your handling code here:
        MenuPrincipal menuP = new MenuPrincipal();
        Connection conn1 = null;
        PreparedStatement ps = null;
        ResultSet rs = null;
        String correo = typeUser.getText();
        String pass = String.valueOf(typePass.getPassword());

        if (correo.equals("Ingrese su em@il")) {
            this.alertaCorreo.setForeground(Color.red);
        }
        if (pass.equals("**********")) {
            this.alertaClave.setForeground(Color.red);
        }
        try {
            conn1 = Conectar();
            ps = conn1.prepareStatement("select correoVendedor, passw  from vendedores where correoVendedor = '" + correo + "' and passw = '" + pass + "'");
            rs = ps.executeQuery();
            if (rs.next()) {
                Connection conn2 = null;
                PreparedStatement ps2 = null;
                ResultSet rs2 = null;
                try {
                    conn2 = Conectar();
                    ps2 = conn2.prepareStatement("select nombreVendedor  from vendedores where correoVendedor = '" + correo + "' ");
                    rs2 = ps2.executeQuery();
                    if (rs2.next()) {
                        String nombreMenu = rs2.getString(1);
                        this.nombre = nombreMenu;
                    }
                } catch (Exception e) {
                    System.out.println(e.toString());
                }
                MenuPrincipal menu = new MenuPrincipal();
                menu.nombreAccount(this.nombre);
                menu.nombre(this.nombre);
                menu.setVisible(true);
                dispose();
            } else {
                this.alertaCredenciales.setForeground(Color.red);
            }
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }//GEN-LAST:event_logTextButtonMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioSesion().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Header;
    private javax.swing.JLabel LogText;
    private javax.swing.JLabel LogoL;
    private javax.swing.JLabel alertaClave;
    private javax.swing.JLabel alertaCorreo;
    private javax.swing.JLabel alertaCredenciales;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel bgBlue;
    private javax.swing.JPanel bglogButton;
    private javax.swing.JPanel exitButton;
    private javax.swing.JLabel exitText;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel logTextButton;
    private javax.swing.JLabel passText;
    private javax.swing.JLabel registroText;
    private javax.swing.JPasswordField typePass;
    private javax.swing.JTextField typeUser;
    private javax.swing.JLabel userText;
    // End of variables declaration//GEN-END:variables
}
