/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import java.awt.Color;
import static java.awt.Color.black;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author gblan
 */
public class newAccount extends javax.swing.JFrame {

    /**
     * Creates new form newAccount
     */
    int xPos, yPos;

    public Connection Conectar() {
        Connection conn = null;

        try {
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/sistemafacturacion", "root", "Wolfhack0504");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No se puedo realizar la conexion" + e.toString());
        }
        return conn;
    }

    public newAccount() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        exitBtn = new javax.swing.JPanel();
        exitText = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        logoIcon = new javax.swing.JLabel();
        registerText = new javax.swing.JLabel();
        apellidoText = new javax.swing.JLabel();
        typeName = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        nameText = new javax.swing.JLabel();
        typeApellido = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        phoneText = new javax.swing.JLabel();
        typePhone = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        emailText = new javax.swing.JLabel();
        typeEmail = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        passText = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        registerBtn = new javax.swing.JPanel();
        textRegister = new javax.swing.JLabel();
        logAccount = new javax.swing.JLabel();
        typePass = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemafacturacion/imagenes/fondo azul.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 0, 440, 720));

        exitBtn.setBackground(new java.awt.Color(255, 255, 255));

        exitText.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        exitText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitText.setText("X");
        exitText.setPreferredSize(new java.awt.Dimension(40, 40));
        exitText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitTextMouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitBtnLayout = new javax.swing.GroupLayout(exitBtn);
        exitBtn.setLayout(exitBtnLayout);
        exitBtnLayout.setHorizontalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exitBtnLayout.createSequentialGroup()
                .addComponent(exitText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        exitBtnLayout.setVerticalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exitBtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(exitText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bg.add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 40));

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1290, Short.MAX_VALUE)
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        bg.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 50));

        logoIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemafacturacion/imagenes/LogoEmpresa (1).png"))); // NOI18N
        logoIcon.setText("jLabel3");
        bg.add(logoIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 180, 50));

        registerText.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        registerText.setText("Crear Cuenta");
        bg.add(registerText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        apellidoText.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        apellidoText.setText("Apellido");
        bg.add(apellidoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        typeName.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        typeName.setForeground(new java.awt.Color(153, 153, 153));
        typeName.setText("Ingrese su nombre");
        typeName.setBorder(null);
        typeName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                typeNameMousePressed(evt);
            }
        });
        bg.add(typeName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 390, 40));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 600, 530, 10));

        nameText.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        nameText.setText("Nombre");
        bg.add(nameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        typeApellido.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        typeApellido.setForeground(new java.awt.Color(153, 153, 153));
        typeApellido.setText("Ingrese sus apellidos");
        typeApellido.setBorder(null);
        typeApellido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                typeApellidoMousePressed(evt);
            }
        });
        bg.add(typeApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 390, 40));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 530, 10));

        phoneText.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        phoneText.setText("Telefono");
        bg.add(phoneText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        typePhone.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        typePhone.setForeground(new java.awt.Color(153, 153, 153));
        typePhone.setText("Ingrese su número telefonico");
        typePhone.setBorder(null);
        typePhone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                typePhoneMousePressed(evt);
            }
        });
        bg.add(typePhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 390, 40));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 530, 10));

        emailText.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        emailText.setText("Email");
        bg.add(emailText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, -1));

        typeEmail.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        typeEmail.setForeground(new java.awt.Color(153, 153, 153));
        typeEmail.setText("Ingrese su correo");
        typeEmail.setBorder(null);
        typeEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                typeEmailMousePressed(evt);
            }
        });
        typeEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeEmailActionPerformed(evt);
            }
        });
        bg.add(typeEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 390, 40));

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 530, 10));

        passText.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        passText.setText("Contraseña");
        bg.add(passText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, -1, -1));

        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 530, 10));

        registerBtn.setBackground(new java.awt.Color(1, 73, 97));

        textRegister.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        textRegister.setForeground(new java.awt.Color(255, 255, 255));
        textRegister.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textRegister.setText("Registrar");
        textRegister.setToolTipText("");
        textRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textRegisterMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                textRegisterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                textRegisterMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                textRegisterMousePressed(evt);
            }
        });

        javax.swing.GroupLayout registerBtnLayout = new javax.swing.GroupLayout(registerBtn);
        registerBtn.setLayout(registerBtnLayout);
        registerBtnLayout.setHorizontalGroup(
            registerBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerBtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(textRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        registerBtnLayout.setVerticalGroup(
            registerBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerBtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(textRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bg.add(registerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 630, 180, 40));

        logAccount.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        logAccount.setText("¿Ya tienes cuenta? Ingresa aquí");
        logAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logAccountMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logAccountMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logAccountMouseExited(evt);
            }
        });
        bg.add(logAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 650, -1, -1));

        typePass.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        typePass.setForeground(new java.awt.Color(153, 153, 153));
        typePass.setText("**********");
        typePass.setBorder(null);
        typePass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                typePassMousePressed(evt);
            }
        });
        bg.add(typePass, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, 390, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void typeEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeEmailActionPerformed

    private void logAccountMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logAccountMouseEntered
        logAccount.setForeground(new Color(1, 73, 97));

    }//GEN-LAST:event_logAccountMouseEntered

    private void logAccountMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logAccountMouseExited
        logAccount.setForeground(black);

    }//GEN-LAST:event_logAccountMouseExited

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        // TODO add your handling code here:
        xPos = evt.getX();
        yPos = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xPos, y - yPos);
    }//GEN-LAST:event_headerMouseDragged

    private void exitTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTextMouseClicked
        // TODO add your handling code here:
        System.exit(0);

    }//GEN-LAST:event_exitTextMouseClicked

    private void exitTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTextMouseEntered
        // TODO add your handling code here:
        exitBtn.setBackground(Color.red);
        exitText.setForeground(Color.white);
    }//GEN-LAST:event_exitTextMouseEntered

    private void exitTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTextMouseExited
        // TODO add your handling code here:
        exitBtn.setBackground(Color.white);
        exitText.setForeground(Color.black);
    }//GEN-LAST:event_exitTextMouseExited

    private void textRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textRegisterMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_textRegisterMouseClicked

    private void textRegisterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textRegisterMouseEntered
        // TODO add your handling code here:
        registerBtn.setBackground(new Color(2, 123, 164));

    }//GEN-LAST:event_textRegisterMouseEntered

    private void textRegisterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textRegisterMouseExited
        // TODO add your handling code here:
        registerBtn.setBackground(new Color(1, 73, 97));

    }//GEN-LAST:event_textRegisterMouseExited

    private void typeNameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_typeNameMousePressed
        // TODO add your handling code here:
        if (typeName.getText().equals("Ingrese su nombre")) {
            typeName.setText("");
            typeName.setForeground(Color.black);
        }
        if (String.valueOf(typePass.getPassword()).isEmpty()) {
            typePass.setText("**********");
            typePass.setForeground(Color.gray);
        }

        if (typeApellido.getText().isEmpty()) {
            typeApellido.setText("Ingrese sus apellidos");
            typeApellido.setForeground(Color.gray);
        }

        if (typePhone.getText().isEmpty()) {
            typePhone.setText("Ingrese su número telefonico");
            typePhone.setForeground(Color.gray);
        }

        if (typeEmail.getText().isEmpty()) {
            typeEmail.setText("Ingrese su correo");
            typeEmail.setForeground(Color.gray);
        }

    }//GEN-LAST:event_typeNameMousePressed

    private void typeApellidoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_typeApellidoMousePressed
        // TODO add your handling code here:
        if (typeName.getText().isEmpty()) {
            typeName.setText("Ingrese su nombre");
            typeName.setForeground(Color.gray);
        }
        if (String.valueOf(typePass.getPassword()).isEmpty()) {
            typePass.setText("**********");
            typePass.setForeground(Color.gray);
        }

        if (typeApellido.getText().equals("Ingrese sus apellidos")) {
            typeApellido.setText("");
            typeApellido.setForeground(Color.black);
        }

        if (typePhone.getText().isEmpty()) {
            typePhone.setText("Ingrese su número telefonico");
            typePhone.setForeground(Color.gray);
        }

        if (typeEmail.getText().isEmpty()) {
            typeEmail.setText("Ingrese su correo");
            typeEmail.setForeground(Color.gray);
        }
    }//GEN-LAST:event_typeApellidoMousePressed

    private void typePhoneMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_typePhoneMousePressed
        // TODO add your handling code here:
        if (typeName.getText().isEmpty()) {
            typeName.setText("Ingrese su nombre");
            typeName.setForeground(Color.gray);
        }
        if (String.valueOf(typePass.getPassword()).isEmpty()) {
            typePass.setText("**********");
            typePass.setForeground(Color.gray);
        }

        if (typeApellido.getText().isEmpty()) {
            typeApellido.setText("Ingrese sus apellidos");
            typeApellido.setForeground(Color.gray);
        }

        if (typePhone.getText().equals("Ingrese su número telefonico")) {
            typePhone.setText("");
            typePhone.setForeground(Color.black);
        }

        if (typeEmail.getText().isEmpty()) {
            typeEmail.setText("Ingrese su correo");
            typeEmail.setForeground(Color.gray);
        }
    }//GEN-LAST:event_typePhoneMousePressed

    private void typeEmailMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_typeEmailMousePressed
        // TODO add your handling code here:
        if (typeName.getText().isEmpty()) {
            typeName.setText("Ingrese su nombre");
            typeName.setForeground(Color.gray);
        }
        if (String.valueOf(typePass.getPassword()).isEmpty()) {
            typePass.setText("**********");
            typePass.setForeground(Color.gray);
        }

        if (typeApellido.getText().isEmpty()) {
            typeApellido.setText("Ingrese sus apellidos");
            typeApellido.setForeground(Color.gray);
        }

        if (typePhone.getText().isEmpty()) {
            typePhone.setText("Ingrese su número telefonico");
            typePhone.setForeground(Color.gray);
        }

        if (typeEmail.getText().equals("Ingrese su correo")) {
            typeEmail.setText("");
            typeEmail.setForeground(Color.black);
        }
    }//GEN-LAST:event_typeEmailMousePressed

    private void typePassMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_typePassMousePressed
        // TODO add your handling code here:
        if (typeName.getText().isEmpty()) {
            typeName.setText("Ingrese su nombre");
            typeName.setForeground(Color.gray);
        }
        if (String.valueOf(typePass.getPassword()).equals("**********")) {
            typePass.setText("");
            typePass.setForeground(Color.black);
        }

        if (typeApellido.getText().isEmpty()) {
            typeApellido.setText("Ingrese sus apellidos");
            typeApellido.setForeground(Color.gray);
        }

        if (typePhone.getText().isEmpty()) {
            typePhone.setText("Ingrese su número telefonico");
            typePhone.setForeground(Color.gray);
        }

        if (typeEmail.getText().isEmpty()) {
            typeEmail.setText("Ingrese su correo");
            typeEmail.setForeground(Color.gray);
        }
    }//GEN-LAST:event_typePassMousePressed

    private void logAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logAccountMouseClicked
        // TODO add your handling code here:
        InicioSesion log = new InicioSesion();
        log.setVisible(true);
        dispose();

    }//GEN-LAST:event_logAccountMouseClicked

    private void textRegisterMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textRegisterMousePressed
        // TODO add your handling code here:
        String nombre = this.typeName.getText();
        String apellido = this.typeApellido.getText();
        String telefono = this.typePhone.getText();
        String correoVendedor = this.typeEmail.getText();
        String passVendedor = String.valueOf(this.typePass.getPassword());
        String query = "INSERT INTO vendedores (nombreVendedor, apellidoVendedor,telefonoVendedor,correoVendedor,passw) VALUES (?,?,?,?,?) ";
        try {
            Connection connet = Conectar();
            PreparedStatement ps = connet.prepareStatement(query);
            ps.setString(1, nombre);
            ps.setString(2, apellido);
            ps.setString(3, telefono);
            ps.setString(4, correoVendedor);
            ps.setString(5, passVendedor);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Registro exitoso");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }//GEN-LAST:event_textRegisterMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apellidoText;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel emailText;
    private javax.swing.JPanel exitBtn;
    private javax.swing.JLabel exitText;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel logAccount;
    private javax.swing.JLabel logoIcon;
    private javax.swing.JLabel nameText;
    private javax.swing.JLabel passText;
    private javax.swing.JLabel phoneText;
    private javax.swing.JPanel registerBtn;
    private javax.swing.JLabel registerText;
    private javax.swing.JLabel textRegister;
    private javax.swing.JTextField typeApellido;
    private javax.swing.JTextField typeEmail;
    private javax.swing.JTextField typeName;
    private javax.swing.JPasswordField typePass;
    private javax.swing.JTextField typePhone;
    // End of variables declaration//GEN-END:variables
}
