/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Interfaces;

import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gblan
 */
public class Terrenos extends javax.swing.JInternalFrame {

    DefaultTableModel modelo;

    /**
     * Creates new form Terrenos
     *
     */
    public Connection Conectar() {
        Connection conn = null;

        try {
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/sistemafacturacion", "root", "Wolfhack0504");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No se puedo realizar la conexion" + e.toString());
        }
        return conn;
    }

    public Terrenos() {

        initComponents();
        infoTable.getTableHeader().setFont(new Font("Roboto Light", Font.BOLD, 14));
        infoTable.getTableHeader().setOpaque(false);
        infoTable.getTableHeader().setBackground(new Color(32, 136, 203));
        infoTable.getTableHeader().setForeground(new Color(255, 255, 255));
        infoTable.setRowHeight(25);

        modelo = new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("Descripción");
        modelo.addColumn("Precio");
        modelo.addColumn("Habitaciones");
        modelo.addColumn("Baños");
        modelo.addColumn("Garaje");
        modelo.addColumn("Vendedor ID");
        modelo.addColumn("Comprador ID");
        this.infoTable.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        descripText = new javax.swing.JLabel();
        typeCost = new javax.swing.JTextField();
        costText = new javax.swing.JLabel();
        typeDescrip = new javax.swing.JTextField();
        roomText = new javax.swing.JLabel();
        typeRoom = new javax.swing.JTextField();
        bathText = new javax.swing.JLabel();
        typeBath = new javax.swing.JTextField();
        table = new javax.swing.JScrollPane();
        infoTable = new javax.swing.JTable();
        cocheraText = new javax.swing.JLabel();
        typeCochera = new javax.swing.JTextField();
        newBtn = new javax.swing.JPanel();
        newText = new javax.swing.JLabel();
        deleteBtn = new javax.swing.JPanel();
        deleteText = new javax.swing.JLabel();
        updateBtn = new javax.swing.JPanel();
        updateText = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(null);
        setPreferredSize(new java.awt.Dimension(910, 690));

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemafacturacion/imagenes/LogoEmpresa (1).png"))); // NOI18N
        logo.setText("jLabel1");

        titulo.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        titulo.setText("Registro de Propiedades");

        descripText.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        descripText.setText("Descripción:");

        typeCost.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        typeCost.setForeground(new java.awt.Color(153, 153, 153));
        typeCost.setText("$5000");
        typeCost.setBorder(null);
        typeCost.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                typeCostMousePressed(evt);
            }
        });
        typeCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeCostActionPerformed(evt);
            }
        });

        costText.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        costText.setText("Precio:");

        typeDescrip.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        typeDescrip.setForeground(new java.awt.Color(153, 153, 153));
        typeDescrip.setText("250m este del centro de sabanilla, 150m2");
        typeDescrip.setBorder(null);
        typeDescrip.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                typeDescripMousePressed(evt);
            }
        });
        typeDescrip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeDescripActionPerformed(evt);
            }
        });

        roomText.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        roomText.setText("Habitaciones:");

        typeRoom.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        typeRoom.setForeground(new java.awt.Color(153, 153, 153));
        typeRoom.setText("2");
        typeRoom.setBorder(null);
        typeRoom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                typeRoomMousePressed(evt);
            }
        });
        typeRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeRoomActionPerformed(evt);
            }
        });

        bathText.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        bathText.setText("Baños: ");

        typeBath.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        typeBath.setForeground(new java.awt.Color(153, 153, 153));
        typeBath.setText("3");
        typeBath.setBorder(null);
        typeBath.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                typeBathMousePressed(evt);
            }
        });

        infoTable.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        infoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Descripción", "Precio", "Habitaciones", "Baños", "Garaje", "Vendedor ID", "Comprador ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        infoTable.setFocusable(false);
        infoTable.setRowHeight(25);
        infoTable.setSelectionBackground(new java.awt.Color(232, 57, 95));
        infoTable.setSelectionForeground(new java.awt.Color(255, 255, 255));
        infoTable.setShowGrid(false);
        infoTable.setShowHorizontalLines(true);
        infoTable.getTableHeader().setReorderingAllowed(false);
        table.setViewportView(infoTable);

        cocheraText.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        cocheraText.setText("Garaje:");

        typeCochera.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        typeCochera.setForeground(new java.awt.Color(153, 153, 153));
        typeCochera.setText("2");
        typeCochera.setBorder(null);
        typeCochera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                typeCocheraMousePressed(evt);
            }
        });

        newBtn.setBackground(new java.awt.Color(1, 73, 97));

        newText.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        newText.setForeground(new java.awt.Color(255, 255, 255));
        newText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newText.setText("Nueva");
        newText.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        newText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                newTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                newTextMouseExited(evt);
            }
        });

        javax.swing.GroupLayout newBtnLayout = new javax.swing.GroupLayout(newBtn);
        newBtn.setLayout(newBtnLayout);
        newBtnLayout.setHorizontalGroup(
            newBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newBtnLayout.createSequentialGroup()
                .addComponent(newText, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        newBtnLayout.setVerticalGroup(
            newBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(newText, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        );

        deleteBtn.setBackground(new java.awt.Color(1, 73, 97));

        deleteText.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        deleteText.setForeground(new java.awt.Color(255, 255, 255));
        deleteText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        deleteText.setText("Eliminar");
        deleteText.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deleteTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deleteTextMouseExited(evt);
            }
        });

        javax.swing.GroupLayout deleteBtnLayout = new javax.swing.GroupLayout(deleteBtn);
        deleteBtn.setLayout(deleteBtnLayout);
        deleteBtnLayout.setHorizontalGroup(
            deleteBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteBtnLayout.createSequentialGroup()
                .addComponent(deleteText, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        deleteBtnLayout.setVerticalGroup(
            deleteBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(deleteText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        );

        updateBtn.setBackground(new java.awt.Color(1, 73, 97));

        updateText.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        updateText.setForeground(new java.awt.Color(255, 255, 255));
        updateText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        updateText.setText("Actualizar");
        updateText.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updateText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updateTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updateTextMouseExited(evt);
            }
        });

        javax.swing.GroupLayout updateBtnLayout = new javax.swing.GroupLayout(updateBtn);
        updateBtn.setLayout(updateBtnLayout);
        updateBtnLayout.setHorizontalGroup(
            updateBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateBtnLayout.createSequentialGroup()
                .addComponent(updateText, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        updateBtnLayout.setVerticalGroup(
            updateBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(updateText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        );

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(table, javax.swing.GroupLayout.PREFERRED_SIZE, 852, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(roomText)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator4)
                                    .addComponent(jSeparator5)
                                    .addComponent(typeRoom))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(titulo)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(newBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(111, 111, 111)))
                        .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(costText)
                            .addComponent(descripText)
                            .addComponent(bathText)
                            .addComponent(cocheraText))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(typeCochera)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(typeCost)
                            .addComponent(typeDescrip, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                            .addComponent(jSeparator6)
                            .addComponent(jSeparator7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(typeBath))
                        .addGap(433, 433, 433))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titulo))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(newBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(descripText)
                            .addComponent(typeDescrip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(costText)
                            .addComponent(typeCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(roomText)
                            .addComponent(typeRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bathText)
                    .addComponent(typeBath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cocheraText)
                            .addComponent(typeCochera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(table, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newTextMouseClicked
        // Falta Definir que sigue

        String[] datos = new String[8];
        datos[0] = ""; //Aqui va el ID de la propiedad ud verá como lo extrae de la base de datos
        datos[1] = typeDescrip.getText();
        datos[2] = typeCost.getText();
        datos[3] = typeRoom.getText();
        datos[4] = typeBath.getText();
        datos[5] = typeCochera.getText();
        datos[6] = "";
        datos[7] = "";

        String query = "INSERT INTO propiedades (tituloPropiedad, precioPropiedad,habitacionesPropiedad,"
                + "wcPropiedad,vendedores_idVendedores,clientes_idClientes,garaje) VALUES (?,?,?,?,?,?,?) ";
        try {
            Connection connet = Conectar();
            PreparedStatement ps = connet.prepareStatement(query);
            ps.setString(1, datos[1]);
            ps.setDouble(2,Double.parseDouble(datos[2]) );
            ps.setInt(3, Integer.parseInt(datos[3]));
            ps.setInt(4, Integer.parseInt(datos[4]));
            ps.setInt(5,0 );
            ps.setInt(6, 0);
            ps.setInt(7, Integer.parseInt(datos[5]));

            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Registro exitoso");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }

        typeDescrip.setText("250m este del centro de sabanilla, 150m2");
        typeDescrip.setForeground(Color.gray);
        typeCost.setText("$5000");
        typeCost.setForeground(Color.gray);
        typeRoom.setText("2");
        typeRoom.setForeground(Color.gray);
        typeBath.setText("3");
        typeBath.setForeground(Color.gray);
        typeCochera.setText("2");
        typeCochera.setForeground(Color.gray);

    }//GEN-LAST:event_newTextMouseClicked

    private void newTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newTextMouseEntered
        // TODO add your handling code here:
        newBtn.setBackground(new Color(2, 123, 164));

    }//GEN-LAST:event_newTextMouseEntered

    private void newTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newTextMouseExited
        // TODO add your handling code here:
        newBtn.setBackground(new Color(1, 73, 97));

    }//GEN-LAST:event_newTextMouseExited

    private void updateTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateTextMouseClicked
        // TODO add your handling code here:


    }//GEN-LAST:event_updateTextMouseClicked

    private void updateTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateTextMouseEntered
        // TODO add your handling code here:
        updateBtn.setBackground(new Color(2, 123, 164));

    }//GEN-LAST:event_updateTextMouseEntered

    private void updateTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateTextMouseExited
        // TODO add your handling code here:
        updateBtn.setBackground(new Color(1, 73, 97));

    }//GEN-LAST:event_updateTextMouseExited

    private void deleteTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteTextMouseClicked
        // TODO add your handling code here:
        int fila = infoTable.getSelectedRow();
        if (fila >= 0) {
            modelo.removeRow(fila);
        } else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar una fila para poder eliminar.");
        }
    }//GEN-LAST:event_deleteTextMouseClicked

    private void deleteTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteTextMouseEntered
        // TODO add your handling code here:
        deleteBtn.setBackground(new Color(2, 123, 164));

    }//GEN-LAST:event_deleteTextMouseEntered

    private void deleteTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteTextMouseExited
        // TODO add your handling code here:
        deleteBtn.setBackground(new Color(1, 73, 97));

    }//GEN-LAST:event_deleteTextMouseExited

    private void typeDescripActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeDescripActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeDescripActionPerformed

    private void typeCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeCostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeCostActionPerformed

    private void typeRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeRoomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeRoomActionPerformed

    private void typeDescripMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_typeDescripMousePressed
        // TODO add your handling code here:
        if (typeDescrip.getText().equals("250m este del centro de sabanilla, 150m2")) {
            typeDescrip.setText("");
            typeDescrip.setForeground(Color.black);
        }
        if (typeCost.getText().isEmpty()) {
            typeCost.setText("$5000");
            typeCost.setForeground(Color.gray);
        }

        if (typeRoom.getText().isEmpty()) {
            typeRoom.setText("2");
            typeRoom.setForeground(Color.gray);
        }

        if (typeBath.getText().isEmpty()) {
            typeBath.setText("3");
            typeBath.setForeground(Color.gray);
        }

        if (typeCochera.getText().isEmpty()) {
            typeCochera.setText("2");
            typeCochera.setForeground(Color.gray);
        }

    }//GEN-LAST:event_typeDescripMousePressed

    private void typeCostMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_typeCostMousePressed
        // TODO add your handling code here:
        if (typeDescrip.getText().isEmpty()) {
            typeDescrip.setText("250m este del centro de sabanilla, 150m2");
            typeDescrip.setForeground(Color.gray);
        }
        if (typeCost.getText().equals("$5000")) {
            typeCost.setText("");
            typeCost.setForeground(Color.black);
        }

        if (typeRoom.getText().isEmpty()) {
            typeRoom.setText("2");
            typeRoom.setForeground(Color.gray);
        }

        if (typeBath.getText().isEmpty()) {
            typeBath.setText("3");
            typeBath.setForeground(Color.gray);
        }

        if (typeCochera.getText().isEmpty()) {
            typeCochera.setText("2");
            typeCochera.setForeground(Color.gray);
        }

    }//GEN-LAST:event_typeCostMousePressed

    private void typeRoomMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_typeRoomMousePressed
        // TODO add your handling code here:
        if (typeDescrip.getText().isEmpty()) {
            typeDescrip.setText("250m este del centro de sabanilla, 150m2");
            typeDescrip.setForeground(Color.gray);
        }
        if (typeCost.getText().isEmpty()) {
            typeCost.setText("$5000");
            typeCost.setForeground(Color.gray);
        }

        if (typeRoom.getText().equals("2")) {
            typeRoom.setText("");
            typeRoom.setForeground(Color.black);
        }

        if (typeBath.getText().isEmpty()) {
            typeBath.setText("3");
            typeBath.setForeground(Color.gray);
        }

        if (typeCochera.getText().isEmpty()) {
            typeCochera.setText("2");
            typeCochera.setForeground(Color.gray);
        }
    }//GEN-LAST:event_typeRoomMousePressed

    private void typeBathMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_typeBathMousePressed
        // TODO add your handling code here:
        if (typeDescrip.getText().isEmpty()) {
            typeDescrip.setText("250m este del centro de sabanilla, 150m2");
            typeDescrip.setForeground(Color.gray);
        }
        if (typeCost.getText().isEmpty()) {
            typeCost.setText("$5000");
            typeCost.setForeground(Color.gray);
        }

        if (typeRoom.getText().isEmpty()) {
            typeRoom.setText("2");
            typeRoom.setForeground(Color.gray);
        }

        if (typeBath.getText().equals("3")) {
            typeBath.setText("");
            typeBath.setForeground(Color.black);
        }

        if (typeCochera.getText().isEmpty()) {
            typeCochera.setText("2");
            typeCochera.setForeground(Color.gray);
        }
    }//GEN-LAST:event_typeBathMousePressed

    private void typeCocheraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_typeCocheraMousePressed
        // TODO add your handling code here:
        if (typeDescrip.getText().isEmpty()) {
            typeDescrip.setText("250m este del centro de sabanilla, 150m2");
            typeDescrip.setForeground(Color.gray);
        }
        if (typeCost.getText().isEmpty()) {
            typeCost.setText("$5000");
            typeCost.setForeground(Color.gray);
        }

        if (typeRoom.getText().isEmpty()) {
            typeRoom.setText("2");
            typeRoom.setForeground(Color.gray);
        }

        if (typeBath.getText().isEmpty()) {
            typeBath.setText("3");
            typeBath.setForeground(Color.gray);
        }

        if (typeCochera.getText().equals("2")) {
            typeCochera.setText("");
            typeCochera.setForeground(Color.black);
        }
    }//GEN-LAST:event_typeCocheraMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bathText;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel cocheraText;
    private javax.swing.JLabel costText;
    private javax.swing.JPanel deleteBtn;
    private javax.swing.JLabel deleteText;
    private javax.swing.JLabel descripText;
    private javax.swing.JTable infoTable;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel newBtn;
    private javax.swing.JLabel newText;
    private javax.swing.JLabel roomText;
    private javax.swing.JScrollPane table;
    private javax.swing.JLabel titulo;
    private javax.swing.JTextField typeBath;
    private javax.swing.JTextField typeCochera;
    private javax.swing.JTextField typeCost;
    private javax.swing.JTextField typeDescrip;
    private javax.swing.JTextField typeRoom;
    private javax.swing.JPanel updateBtn;
    private javax.swing.JLabel updateText;
    // End of variables declaration//GEN-END:variables
}
