/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Interfaces;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author xbyro
 */
public class Ventas extends javax.swing.JInternalFrame {

    /**
     * Creates new form Ventas
     */
    public Connection Conectar() {
        Connection conn = null;

        try {
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/sistemafacturacion", "root", "Wolfhack0504");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No se puedo realizar la conexion" + e.toString());
        }
        return conn;
    }
    DefaultTableModel modelo;

    public Ventas() {
        initComponents();
        this.setSize(new Dimension(910, 690));
        this.setTitle("Ventas");
        infoTable.getTableHeader().setFont(new Font("Roboto Light", Font.BOLD, 14));
        infoTable.getTableHeader().setOpaque(false);
        infoTable.getTableHeader().setBackground(new Color(32, 136, 203));
        infoTable.getTableHeader().setForeground(new Color(255, 255, 255));
        infoTable.setRowHeight(25);

        modelo = new DefaultTableModel();
        modelo.addColumn("N° Factura");
        modelo.addColumn("Fecha");
        modelo.addColumn("Cliente");
        modelo.addColumn("Propiedad");
        modelo.addColumn("SubTotal");
        modelo.addColumn("Descuento");
        modelo.addColumn("Impuesto");
        modelo.addColumn("Total");
        modelo.addColumn("Vendedor_ID");

        this.infoTable.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        LogoL = new javax.swing.JLabel();
        VenText = new javax.swing.JLabel();
        numText = new javax.swing.JLabel();
        numAI = new javax.swing.JLabel();
        clientText = new javax.swing.JLabel();
        clientBox = new javax.swing.JComboBox<>();
        dateText = new javax.swing.JLabel();
        terrenoText = new javax.swing.JLabel();
        typeDate = new javax.swing.JTextField();
        terrenosBox = new javax.swing.JComboBox<>();
        vendedorText = new javax.swing.JLabel();
        vendedorBox = new javax.swing.JComboBox<>();
        subTotalText = new javax.swing.JLabel();
        subTotalAmount = new javax.swing.JLabel();
        impuestoText = new javax.swing.JLabel();
        impuestoAmount = new javax.swing.JLabel();
        totalText = new javax.swing.JLabel();
        totalAmount = new javax.swing.JLabel();
        addBtn = new javax.swing.JButton();
        newBtn = new javax.swing.JButton();
        header = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        table = new javax.swing.JScrollPane();
        infoTable = new javax.swing.JTable();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LogoL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemafacturacion/imagenes/LogoEmpresa (1).png"))); // NOI18N
        LogoL.setText("jLabel1");
        bg.add(LogoL, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 180, 50));

        VenText.setFont(new java.awt.Font("Roboto Black", 1, 36)); // NOI18N
        VenText.setText("VENTAS");
        bg.add(VenText, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, -1, -1));

        numText.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        numText.setText("N° Factura:");
        bg.add(numText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 100, 20));

        numAI.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        numAI.setText("1");
        bg.add(numAI, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 160, -1));

        clientText.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        clientText.setText("Cliente:");
        bg.add(clientText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        clientBox.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        clientBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione cliente..." }));
        clientBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                clientBoxMousePressed(evt);
            }
        });
        bg.add(clientBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 180, -1));

        dateText.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        dateText.setText("Fecha:");
        bg.add(dateText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        terrenoText.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        terrenoText.setText("Propiedad:");
        bg.add(terrenoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        typeDate.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        typeDate.setForeground(new java.awt.Color(153, 153, 153));
        typeDate.setText("12 de marzo de 2022");
        typeDate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                typeDateMousePressed(evt);
            }
        });
        bg.add(typeDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 180, -1));

        terrenosBox.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        terrenosBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione propiedad..." }));
        terrenosBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                terrenosBoxMousePressed(evt);
            }
        });
        bg.add(terrenosBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 180, -1));

        vendedorText.setFont(new java.awt.Font("Raleway Light", 1, 18)); // NOI18N
        vendedorText.setText("Vendedor:");
        bg.add(vendedorText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        vendedorBox.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        vendedorBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione vendedor..." }));
        vendedorBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                vendedorBoxMousePressed(evt);
            }
        });
        bg.add(vendedorBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 180, -1));

        subTotalText.setFont(new java.awt.Font("Raleway Light", 1, 18)); // NOI18N
        subTotalText.setText("SubTotal:");
        bg.add(subTotalText, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 90, -1, -1));

        subTotalAmount.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        subTotalAmount.setText("0.00");
        bg.add(subTotalAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 90, -1, -1));

        impuestoText.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        impuestoText.setText("Impuesto:");
        bg.add(impuestoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 130, -1, -1));

        impuestoAmount.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        impuestoAmount.setText("0.00");
        bg.add(impuestoAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 130, -1, -1));

        totalText.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        totalText.setText("Total:");
        bg.add(totalText, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 180, -1, -1));

        totalAmount.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        totalAmount.setText("0.00");
        bg.add(totalAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 180, -1, -1));

        addBtn.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        addBtn.setText("Agregar Factura");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        bg.add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 280, -1, -1));

        newBtn.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        newBtn.setText("Nueva Factura");
        bg.add(newBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 280, 130, -1));

        header.setBackground(new java.awt.Color(0, 39, 54));

        jLabel15.setFont(new java.awt.Font("Raleway Light", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Ventas Realizadas");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addContainerGap(701, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        bg.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 870, 30));

        infoTable.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        infoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N° Factura", "Fecha", "Cliente", "Propieadad", "SubTotal", "Descuento", "Impuesto", "Total", "Vendedor ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        infoTable.setFocusable(false);
        infoTable.setRowHeight(25);
        infoTable.setSelectionBackground(new java.awt.Color(232, 57, 95));
        infoTable.setSelectionForeground(new java.awt.Color(255, 255, 255));
        infoTable.setShowGrid(false);
        infoTable.setShowHorizontalLines(true);
        infoTable.getTableHeader().setReorderingAllowed(false);
        table.setViewportView(infoTable);

        bg.add(table, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 870, 250));

        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addBtnActionPerformed

    private void typeDateMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_typeDateMousePressed
        // TODO add your handling code here:
        if (typeDate.getText().equals("12 de marzo de 2022")) {
            typeDate.setText("");
            typeDate.setForeground(Color.black);
        }


    }//GEN-LAST:event_typeDateMousePressed

    private void clientBoxMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientBoxMousePressed
        // TODO add your handling code here:
        if (typeDate.getText().isEmpty()) {
            typeDate.setText("12 de marzo de 2022");
            typeDate.setForeground(Color.gray);
        }
    }//GEN-LAST:event_clientBoxMousePressed

    private void terrenosBoxMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_terrenosBoxMousePressed
        // TODO add your handling code here:
        if (typeDate.getText().isEmpty()) {
            typeDate.setText("12 de marzo de 2022");
            typeDate.setForeground(Color.gray);
        }

    }//GEN-LAST:event_terrenosBoxMousePressed

    private void vendedorBoxMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vendedorBoxMousePressed
        // TODO add your handling code here:
        if (typeDate.getText().isEmpty()) {
            typeDate.setText("12 de marzo de 2022");
            typeDate.setForeground(Color.gray);
        }
    }//GEN-LAST:event_vendedorBoxMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LogoL;
    private javax.swing.JLabel VenText;
    private javax.swing.JButton addBtn;
    private javax.swing.JPanel bg;
    private javax.swing.JComboBox<String> clientBox;
    private javax.swing.JLabel clientText;
    private javax.swing.JLabel dateText;
    private javax.swing.JPanel header;
    private javax.swing.JLabel impuestoAmount;
    private javax.swing.JLabel impuestoText;
    private javax.swing.JTable infoTable;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JButton newBtn;
    private javax.swing.JLabel numAI;
    private javax.swing.JLabel numText;
    private javax.swing.JLabel subTotalAmount;
    private javax.swing.JLabel subTotalText;
    private javax.swing.JScrollPane table;
    private javax.swing.JLabel terrenoText;
    private javax.swing.JComboBox<String> terrenosBox;
    private javax.swing.JLabel totalAmount;
    private javax.swing.JLabel totalText;
    private javax.swing.JTextField typeDate;
    private javax.swing.JComboBox<String> vendedorBox;
    private javax.swing.JLabel vendedorText;
    // End of variables declaration//GEN-END:variables
}
